In [1]:
def opindia(uri):
    from bs4 import BeautifulSoup
    import requests
    url = uri
    data = requests.get(url)
    soup = BeautifulSoup(data.content)
    
    for i in soup.find_all("h1",class_={"tdb-title-text"}):
        title = i.text
    article = ""
    for i in soup.find_all("div",class_={"tdb-block-inner td-fix-index"}):
        article = article + str(i.text)
    date = article[0:23]
    date = date.replace(",","")
    return title,article,date
   

In [2]:
opindia("https://www.opindia.com/2021/07/saket-gokhale-lakshmi-puri-deletes-tweets-delhi-high-court/")

('Saket Gokhale voluntarily deletes tweets he vowed not to voluntarily delete, all tweets on Lakshmi Puri removed: Details',
 "Wednesday, November 24, 2021HomeNews ReportsSaket Gokhale voluntarily deletes tweets he vowed not to voluntarily delete, all tweets on...Updated: 16 July, 2021 Saket Gokhale voluntarily deletes tweets he vowed not to voluntarily delete, all tweets on Lakshmi Puri removed: DetailsWhen one clicks on the link to the tweet, it says that the tweet does not exist. Intriguingly, Saket Gokhale had told the Court that he would not voluntarily delete the thread.16 July, 2021 OpIndia Staff\n\n4209\n\n\n    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1632223042378-0'); });\n  \n\nRahul Gandhi fanboy Saket Gokhale has deleted the tweets where he made unfounded allegations against Lakshmi Puri, wife of Union Minister Hardeep Singh Puri. Saket Gokhale alleged that Puri bought a house worth $2.5 million in Switzerland, for which the couple did not have enough

In [3]:
def findurls_inapage(baseurl):
    from bs4 import BeautifulSoup
    import requests
    url = baseurl
    data = requests.get(url)
    soup = BeautifulSoup(data.content)
    urlsinapage = []
    for i in soup.find_all("div",class_={"td_block_inner tdb-block-inner td-fix-index"}):
        for j in i.find_all("a",class_={"td-image-wrap"}):
            urlsinapage.append(j['href'])
    return urlsinapage

In [4]:
findurls_inapage('https://www.opindia.com/2021/07/page/4/')

['https://www.opindia.com/2021/07/license-khan-chacha-restaurant-run-by-navneet-kalra-cancelled-details/',
 'https://www.opindia.com/2021/07/afghanistan-national-resistance-movement-against-taliban-vice-president-amrullah-saleh/',
 'https://www.opindia.com/2021/07/border-clash-mizoram-govt-fir-assam-chief-minister-himanta-biswa-sarma-details/',
 'https://www.opindia.com/2021/07/anti-terror-ngo-gifct-labels-bjp-as-non-violent-extremist-fringe-group/',
 'https://www.opindia.com/2021/07/friendship-ended-with-mudasir-meme-nft/',
 'https://www.opindia.com/2021/07/bombay-hc-tell-shilpa-shetty-news-reports-based-on-police-case-cant-be-defamatory/',
 'https://www.opindia.com/2021/07/tn-muslims-oppose-sacrifice-of-pigs-by-hindus-saying-it-is-unhygienic/',
 'https://www.opindia.com/2021/07/usa-antifa-journalist-vishal-singh-punched-person-of-colour-andy-ngo/',
 'https://www.opindia.com/2021/07/bharadwaj-speaks-deletes-twitter-account-after-threats-of-legal-action/',
 'https://www.opindia.com/202

In [5]:
baseurls = []

for i in range(2,10,1):
    url = "https://www.opindia.com/2021/07/page/"
    url = url + str(i) + "/"
    baseurls.append(url)
    

In [6]:
baseurls

['https://www.opindia.com/2021/07/page/2/',
 'https://www.opindia.com/2021/07/page/3/',
 'https://www.opindia.com/2021/07/page/4/',
 'https://www.opindia.com/2021/07/page/5/',
 'https://www.opindia.com/2021/07/page/6/',
 'https://www.opindia.com/2021/07/page/7/',
 'https://www.opindia.com/2021/07/page/8/',
 'https://www.opindia.com/2021/07/page/9/']

In [7]:
allurls = []
for i in baseurls:
    allurls.extend(findurls_inapage(i))

In [8]:
allurls

['https://www.opindia.com/2021/07/licypriya-kangujam-samantham-meshram-jai-bhim-annihilation-of-caste-ambedkar/',
 'https://www.opindia.com/2021/07/amazon-and-flipkart-served-notice-for-selling-pregnancy-termination-pills/',
 'https://www.opindia.com/2021/07/delhi-police-arrests-gangster-kala-jathedi-was-operating-gang-links-with-politicians-punjab/',
 'https://www.opindia.com/2021/07/imran-khan-claims-women-given-more-respect-in-islamic-countries/',
 'https://www.opindia.com/2021/07/gold-smuggling-case-outgoing-customs-commissioner-lashes-out-at-kerala-gvt/',
 'https://www.opindia.com/2021/07/indian-ace-shuttler-pv-sindhu-loses-in-semifinal-of-tokyo-olympics-tai-tzu-ying/',
 'https://www.opindia.com/2021/07/the-print-wrongly-uses-sero-survey-to-claim-covid-cases-are-underreported/',
 'https://www.opindia.com/2021/07/did-acquisition-proposal-apple-tesla-lead-tim-cook-tell-elon-must-f-word/',
 'https://www.opindia.com/2021/07/gehana-vasisth-mumbai-police-rs-15-lakhs-porn-case-raj-kundra

In [9]:
titles=[]
articles=[]
dates=[]
for i in allurls:
    t,a,d = opindia(i)
    titles.append(t)
    articles.append(a)
    dates.append(d)

import pandas as pd
Q = pd.DataFrame([dates,titles,articles]).T
Q.columns=["dates","titles","articles"]

In [49]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [50]:
import re
import nltk 

def sw(A3):
  from nltk.corpus import stopwords
  sw = stopwords.words("english")
  A4 = []
  for i in A3:
    if i not in sw:
      A4.append(i)
  return A4

#For Stemming
def stem(A4):
  from nltk.stem.porter import PorterStemmer
  ps = PorterStemmer()
  A5 = []
  for i in A4:
    A5.append(ps.stem(i))
  return A5


#For Lemmetization
def lem(A5):  
  from nltk.stem import WordNetLemmatizer
  wnlmt = WordNetLemmatizer()
  A6 = []
  for i in A5:
    A6.append(wnlmt.lemmatize(i))
  return A6
  

def tokenizer(A):
  from nltk.tokenize import word_tokenize
  A1 = word_tokenize(A)
  return A1

# text preprocessing
def rem_spl_chars(rev):
  rev = rev.lower()
  return re.sub("[^a-zA-Z0-9 ]","",rev)
  
  




In [52]:
Q.head()

dates  ...                                           articles
0  Wednesday November 24  ...  Wednesday, November 24, 2021HomeSocial MediaJa...
1  Wednesday November 24  ...  Wednesday, November 24, 2021HomeNews ReportsMa...
2  Wednesday November 24  ...  Wednesday, November 24, 2021HomeNews ReportsDe...
3  Wednesday November 24  ...  Wednesday, November 24, 2021HomeNews Reports‘W...
4  Wednesday November 24  ...  Wednesday, November 24, 2021HomeNews ReportsAl...

[5 rows x 3 columns]

In [53]:
P1 = []
for i in Q.titles:
    for j in sw(stem(tokenize(rem_spl_chars(i)))):
        P1.append(j)

In [54]:
P1

['jai',
 'bhim',
 'instead',
 'chhota',
 'bheem',
 'eight',
 'year',
 'old',
 'child',
 'use',
 'prop',
 'hi',
 'parent',
 'cast',
 'agenda',
 'maharashtra',
 'drug',
 'regul',
 'issu',
 'notic',
 'amazon',
 'flipkart',
 'sell',
 'pregnanc',
 'termin',
 'pill',
 'without',
 'prescript',
 'delhi',
 'polic',
 'arrest',
 'gangster',
 'kala',
 'jathedi',
 'reveal',
 'wa',
 'oper',
 'gangster',
 'link',
 'politician',
 'punjab',
 'know',
 'far',
 'women',
 'given',
 'far',
 'respect',
 'islam',
 'countri',
 'claim',
 'pakistan',
 'pm',
 'imran',
 'khan',
 'make',
 'uturn',
 'blame',
 'women',
 'cloth',
 'rape',
 'effort',
 'influenc',
 'investig',
 'gold',
 'smuggl',
 'case',
 'fail',
 'outgo',
 'custom',
 'commission',
 'lash',
 'kerala',
 'govt',
 'polic',
 'pv',
 'sindhu',
 'suffer',
 'defeat',
 'tokyo',
 'olymp',
 'semifin',
 'lose',
 'straight',
 'set',
 'world',
 'no1',
 'tai',
 'tzuy',
 'print',
 'use',
 'sero',
 'survey',
 'result',
 'claim',
 '9265',
 'crore',
 'indian',
 'infect',

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
X = tv.fit_transform(P1).toarray()

In [56]:
len(tv.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


766

In [57]:
unique_words = tv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [59]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3)
model = km.fit(X)

In [60]:
model.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [61]:
model.cluster_centers_

array([[0.00095602, 0.00095602, 0.00095602, ..., 0.00095602, 0.00095602,
        0.00095602],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [62]:
Q = pd.DataFrame(model.cluster_centers_).T
Q.index = tv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [63]:
list(enumerate(tv.get_feature_names()))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


[(0, '100'),
 (1, '14'),
 (2, '15'),
 (3, '1500'),
 (4, '20'),
 (5, '2008'),
 (6, '456'),
 (7, '5th'),
 (8, '600'),
 (9, '786'),
 (10, '9265'),
 (11, 'aaryan'),
 (12, 'abduct'),
 (13, 'abus'),
 (14, 'accid'),
 (15, 'account'),
 (16, 'accus'),
 (17, 'ace'),
 (18, 'acquir'),
 (19, 'act'),
 (20, 'actress'),
 (21, 'adjourn'),
 (22, 'afghanistan'),
 (23, 'agenda'),
 (24, 'aggress'),
 (25, 'aid'),
 (26, 'alam'),
 (27, 'alcohol'),
 (28, 'alexand'),
 (29, 'allah'),
 (30, 'alleg'),
 (31, 'allegi'),
 (32, 'allow'),
 (33, 'amargarh'),
 (34, 'amazon'),
 (35, 'american'),
 (36, 'analysi'),
 (37, 'ancient'),
 (38, 'anecdot'),
 (39, 'anim'),
 (40, 'announc'),
 (41, 'anoth'),
 (42, 'antifa'),
 (43, 'antiterror'),
 (44, 'anurag'),
 (45, 'appear'),
 (46, 'appl'),
 (47, 'approach'),
 (48, 'area'),
 (49, 'arora'),
 (50, 'around'),
 (51, 'arrest'),
 (52, 'arrog'),
 (53, 'artefact'),
 (54, 'ask'),
 (55, 'aspir'),
 (56, 'assam'),
 (57, 'assault'),
 (58, 'associ'),
 (59, 'atop'),
 (60, 'attack'),
 (61, 'atten

In [64]:
Q.columns=["A","B","C"]

In [65]:
model.cluster_centers_.argsort()

array([[739, 198, 127, ..., 313, 295, 607],
       [ 51, 725, 141, ..., 256, 765, 739],
       [  0, 496, 497, ..., 248, 110, 198]])

In [66]:
Q

A    B    C
100     0.000956  0.0  0.0
14      0.000956  0.0  0.0
15      0.000956  0.0  0.0
1500    0.000956  0.0  0.0
20      0.000956  0.0  0.0
...          ...  ...  ...
wrong   0.001912  0.0  0.0
year    0.001912  0.0  0.0
yemen   0.000956  0.0  0.0
zoo     0.000956  0.0  0.0
zverev  0.000956  0.0  0.0

[766 rows x 3 columns]

In [67]:
model.cluster_centers_.argsort()

array([[739, 198, 127, ..., 313, 295, 607],
       [ 51, 725, 141, ..., 256, 765, 739],
       [  0, 496, 497, ..., 248, 110, 198]])

In [68]:
common_words = model.cluster_centers_.argsort()[:,:-10:-1]
for num, centroid in enumerate(common_words):
    print(str(num) + ' ' + ','.join(unique_words[word] for word in centroid))

0 say,govt,hindu,india,bjp,claim,accus,file,use
1 wa,zverev,footag,friendship,freedom,free,four,found,fort
2 detail,case,file,indian,india,arrest,wa,claim,polic


In [69]:
list(enumerate(common_words))

[(0, array([607, 295, 313, 329,  91, 141,  16, 248, 725])),
 (1, array([739, 765, 256, 264, 263, 262, 261, 260, 259])),
 (2, array([198, 110, 248, 330, 329,  51, 739, 141, 504]))]

In [70]:
unique_words[95]

'bodi'

In [71]:
from sklearn.decomposition import NMF
nm = NMF(n_components=3, random_state=30)
model = nm.fit(X)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


In [72]:
new_articles = ["Tanishq gives a formal apology to Indians"]
#nm.transform(tf.transform(new_articles)).argsort(axis=1)[:,-1]

In [73]:
nm.transform(tv.transform(new_articles)).argsort()

array([[0, 1, 2]])